version: '3.8'

services:
  apache:
    image: php:8.2-apache
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
      - ./apache/apache2.conf:/etc/apache2/conf-available/custom.conf
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=lamp_user
      - MYSQL_PASSWORD=secure_password
      - MYSQL_DATABASE=lamp_db
    restart: always
    command: >
      sh -c "docker-php-ext-install mysqli pdo pdo_mysql &&
             a2enmod rewrite &&
             apache2-foreground"

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=lamp_db
      - MYSQL_USER=lamp_user
      - MYSQL_PASSWORD=secure_password
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=root_password
    depends_on:
      - mysql
    restart: always

volumes:
  mysql_data: